# Generated by Django 6.0.4 on 2026-04-08 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('left', 'Left'), ('right', 'Right')], max_length=5)),
                ('duration', models.PositiveIntegerField()),
                ('from_airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_routes', to='routes.airport')),
                ('to_airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_routes', to='routes.airport')),
            ],
            options={
                'indexes': [models.Index(fields=['from_airport'], name='routes_rout_from_ai_48e422_idx')],
                'constraints': [models.UniqueConstraint(fields=('from_airport', 'position'), name='unique_position_per_airport')],
            },
        ),
    ]
